dist: trusty
sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install -U pip
- pip install -r requirements.txt
script:
- python -m unittest discover tests
- bash tests/test_k2tf.sh
deploy:
  provider: pypi
  user: twentybn-machine-user
  password:
    secure: "NvZ5dDQQafsqM4MxDuk/FowSWA8EFPv+C98VB2aP7tmRaAD/EaET6ozRfF7oI9Q5GRJEcPgfG/p+RPL1wlVLcVQJWmkAmSVViupF774h2ii5dkCGFl1v7edA6CBFPoZkqBs02mOmAKrqfnI3DfqUurQEEhA+2So2aVqT3uxM0zwO5Db25JJscCylqyzIIc82u0pTw+a2FXRS2cS2YXuh+mLYxgav7M5Ra2giTyGpY4J+LFdGH2s79n9Fy2AgdtMEnOtC2sKl18tpE0aRBV4IZl0vmof2Iz+xtuUru1mFtNrQS59YyD1fD8e/ok9gjRzMIG/gu/EX9eUkzKiuHmFpNODuvBwlJVWvlw7tW/L0i4h/lra1UDRHq8gTbBLnF2uE/969+a6xM6sUwN+56xuili4HvVu6W1iYh/dx+qj73agGJAXpYLABEBO6stInjIX5rOADkpC9lE5Zr2FUI28aXw4dn7EhWPb/NrKgG8Dr/jaG+D+T0BTLacmE3zPj7ICw7tlxknePAYPlAjBgrCJ5JD2tpEsjJtX5ID3FRiaPE8f2xDr8CZyf4D9U57/criRfJLRzebFouMr0B8ip3GJf6sDSh8WdD1vm+eVZ2sx6xhhnhyb6u6WQAIY7YPDMuThg3LIs1XAt8GIZye2qstfbiPRPN/vLZu74z6PSVpea05o="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: TwentyBN/ionn
    python: '3.6'
    branch: master
