sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy
    - source activated test-environment
    - pip install -U pip
    - python setup.py install
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp27-none-linux_x86_64.whl;
      elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
        pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp34-cp34m-linux_x86_64.whl;
      elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
        pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp35-cp35m-linux_x86_64.whl;
      fi
script:
    - python -m unittest discover tests
