dist: trusty
sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
install:
    - pip install -U pip
    - pip install tnt
    - pip install keras
script:
    - python -m unittest discover tests
    - bash tests/test_k2tf.sh
