dist: trusty
sudo: false
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install -U pip
- pip install -r requirements.txt
script:
- python -m unittest discover tests
- bash tests/test_k2tf.sh
deploy:
  provider: pypi
  user: twentybn-machine-user
  password:
    secure: "lcS665likGQmB6yE+Oupdt76B5yAWIDS1s2t4ouEcEnBeYHV1RxY1/wOEyubW1x/Z2/7zrj827eHvm1kiyVtI0ax+FsVUbcDjV8/ow+IGwgItsLPrHF8wpJct9g+VKtzWfC945AZpaT4o17XqbvdbylMOKkyB097ZUP9ZYkJG7eKP+ZFz4trAD8U80mWMB3U0yWCuSKQOd33qtxyh6fv0IgzqKNqWtprELZf1HJZuUlAK+5bLfWnP3hZdB62PwbOOOpaOv2gfPSge0zS765Gmd7gzeX29vqOL6RFVJxYuhno1SoQP4dK259mlmphrABQadNXQ31FHOCd/fgz+WzqV+u4qfl7BZgr7iCEMRMcHFx+jjEe4ECALboqHuRAtDCPDp/CtR50Tu07/6YKYFbnljBlRTBLiaRZoZwz+0sGBJUNLPMfaE4NVRqiZkXmAA688DvLAoM3nAW4FvQXQZnZ/fc8OW9cMCKXqNiALHzDMSdh4lzOm5SA3wJ8P+YHwO3cK/hS2Naf1xkor7NfHasdxriugx8EAyxuyZDjw6U16KsnCx8rYtuIIUNFYl/BCbOWhj/7+kam5NxbXeDSr2LehoEe98ldfe1Tzm0FmtgSpeGY/xrHyw4hokZPq2oMb18zs0e1I+bJgLq/pqGwF7mcnSD8csASon5a9OEQyU2dLHo="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: TwentyBN/ionn
    python: '3.6'
    branch: master
