sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
install:
    - pip install -U pip
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp27-none-linux_x86_64.whl;
      elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
        pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp34-cp34m-linux_x86_64.whl;
      elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
        pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp35-cp35m-linux_x86_64.whl;
      fi
script:
    - locate libc.so
    - python -c "import tensorflow"
